services:
  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: zoomcamp      
      PGADMIN_CONFIG_WTF_CSRF_HEADERS: '["Referer", "Origin"]'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - db

  db:
    image: postgres:12.19
    restart: always          
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: brazil_vra
    ports:
      - "5432:5432"  # Added this line to expose PostgreSQL port
    volumes:                 
      - pg-data:/var/lib/postgresql/data

volumes:
  pgadmin-data:
  pg-data: